/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as FreeRouteImport } from './routes/free'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlcAccessRouteImport } from './routes/alc-access'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ToolsTradingJournalRouteImport } from './routes/tools/trading-journal'
import { Route as ToolsPipCalculatorRouteImport } from './routes/tools/pip-calculator'
import { Route as ToolsMarketSessionsRouteImport } from './routes/tools/market-sessions'
import { Route as PaymentSlugRouteImport } from './routes/payment/$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as CertificatesCertificateIdRouteImport } from './routes/certificates/$certificateId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminTradingTipsRouteImport } from './routes/admin/trading-tips'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminMentorshipApplicationsRouteImport } from './routes/admin/mentorship-applications'
import { Route as AdminLessonsRouteImport } from './routes/admin/lessons'
import { Route as AdminCertificatesRouteImport } from './routes/admin/certificates'
import { Route as AdminAlcLibraryRouteImport } from './routes/admin/alc-library'
import { Route as AdminAlcAccessRouteImport } from './routes/admin/alc-access'
import { Route as AuthenticatedTipsRouteImport } from './routes/_authenticated/tips'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as CoursesSlugIndexRouteImport } from './routes/courses/$slug/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as CoursesSlugLessonSlugRouteImport } from './routes/courses/$slug/$lessonSlug'
import { Route as AdminStudentsStudentIdRouteImport } from './routes/admin/students/$studentId'
import { Route as AuthenticatedDashboardTradingPlanRouteImport } from './routes/_authenticated/dashboard.trading-plan'
import { Route as AuthenticatedDashboardGiftGiftIdRouteImport } from './routes/_authenticated/dashboard.gift.$giftId'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeRoute = FreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlcAccessRoute = AlcAccessRouteImport.update({
  id: '/alc-access',
  path: '/alc-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTradingJournalRoute = ToolsTradingJournalRouteImport.update({
  id: '/trading-journal',
  path: '/trading-journal',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPipCalculatorRoute = ToolsPipCalculatorRouteImport.update({
  id: '/pip-calculator',
  path: '/pip-calculator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMarketSessionsRoute = ToolsMarketSessionsRouteImport.update({
  id: '/market-sessions',
  path: '/market-sessions',
  getParentRoute: () => ToolsRoute,
} as any)
const PaymentSlugRoute = PaymentSlugRouteImport.update({
  id: '/payment/$slug',
  path: '/payment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const CertificatesCertificateIdRoute =
  CertificatesCertificateIdRouteImport.update({
    id: '/certificates/$certificateId',
    path: '/certificates/$certificateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminTradingTipsRoute = AdminTradingTipsRouteImport.update({
  id: '/admin/trading-tips',
  path: '/admin/trading-tips',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMentorshipApplicationsRoute =
  AdminMentorshipApplicationsRouteImport.update({
    id: '/admin/mentorship-applications',
    path: '/admin/mentorship-applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/admin/lessons',
  path: '/admin/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/admin/certificates',
  path: '/admin/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlcLibraryRoute = AdminAlcLibraryRouteImport.update({
  id: '/admin/alc-library',
  path: '/admin/alc-library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlcAccessRoute = AdminAlcAccessRouteImport.update({
  id: '/admin/alc-access',
  path: '/admin/alc-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTipsRoute = AuthenticatedTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CoursesSlugIndexRoute = CoursesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const CoursesSlugLessonSlugRoute = CoursesSlugLessonSlugRouteImport.update({
  id: '/$lessonSlug',
  path: '/$lessonSlug',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const AdminStudentsStudentIdRoute = AdminStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AdminStudentsRoute,
} as any)
const AuthenticatedDashboardTradingPlanRoute =
  AuthenticatedDashboardTradingPlanRouteImport.update({
    id: '/trading-plan',
    path: '/trading-plan',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGiftGiftIdRoute =
  AuthenticatedDashboardGiftGiftIdRouteImport.update({
    id: '/gift/$giftId',
    path: '/gift/$giftId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alc-access': typeof AlcAccessRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faq': typeof FaqRoute
  '/free': typeof FreeRoute
  '/mentorship': typeof MentorshipRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/tips': typeof AuthenticatedTipsRoute
  '/admin/alc-access': typeof AdminAlcAccessRoute
  '/admin/alc-library': typeof AdminAlcLibraryRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/mentorship-applications': typeof AdminMentorshipApplicationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/admin/trading-tips': typeof AdminTradingTipsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/payment/$slug': typeof PaymentSlugRoute
  '/tools/market-sessions': typeof ToolsMarketSessionsRoute
  '/tools/pip-calculator': typeof ToolsPipCalculatorRoute
  '/tools/trading-journal': typeof ToolsTradingJournalRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/dashboard/trading-plan': typeof AuthenticatedDashboardTradingPlanRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/courses/$slug/$lessonSlug': typeof CoursesSlugLessonSlugRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
  '/dashboard/gift/$giftId': typeof AuthenticatedDashboardGiftGiftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alc-access': typeof AlcAccessRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/free': typeof FreeRoute
  '/mentorship': typeof MentorshipRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tips': typeof AuthenticatedTipsRoute
  '/admin/alc-access': typeof AdminAlcAccessRoute
  '/admin/alc-library': typeof AdminAlcLibraryRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/mentorship-applications': typeof AdminMentorshipApplicationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/admin/trading-tips': typeof AdminTradingTipsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/payment/$slug': typeof PaymentSlugRoute
  '/tools/market-sessions': typeof ToolsMarketSessionsRoute
  '/tools/pip-calculator': typeof ToolsPipCalculatorRoute
  '/tools/trading-journal': typeof ToolsTradingJournalRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/dashboard/trading-plan': typeof AuthenticatedDashboardTradingPlanRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/courses/$slug/$lessonSlug': typeof CoursesSlugLessonSlugRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/courses/$slug': typeof CoursesSlugIndexRoute
  '/dashboard/gift/$giftId': typeof AuthenticatedDashboardGiftGiftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/alc-access': typeof AlcAccessRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faq': typeof FaqRoute
  '/free': typeof FreeRoute
  '/mentorship': typeof MentorshipRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tips': typeof AuthenticatedTipsRoute
  '/admin/alc-access': typeof AdminAlcAccessRoute
  '/admin/alc-library': typeof AdminAlcLibraryRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/mentorship-applications': typeof AdminMentorshipApplicationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/admin/trading-tips': typeof AdminTradingTipsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/payment/$slug': typeof PaymentSlugRoute
  '/tools/market-sessions': typeof ToolsMarketSessionsRoute
  '/tools/pip-calculator': typeof ToolsPipCalculatorRoute
  '/tools/trading-journal': typeof ToolsTradingJournalRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/_authenticated/dashboard/trading-plan': typeof AuthenticatedDashboardTradingPlanRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/courses/$slug/$lessonSlug': typeof CoursesSlugLessonSlugRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
  '/_authenticated/dashboard/gift/$giftId': typeof AuthenticatedDashboardGiftGiftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alc-access'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/free'
    | '/mentorship'
    | '/reset-password'
    | '/sitemap.xml'
    | '/testimonials'
    | '/tools'
    | '/dashboard'
    | '/profile'
    | '/tips'
    | '/admin/alc-access'
    | '/admin/alc-library'
    | '/admin/certificates'
    | '/admin/lessons'
    | '/admin/mentorship-applications'
    | '/admin/payments'
    | '/admin/students'
    | '/admin/trading-tips'
    | '/auth/callback'
    | '/certificates/$certificateId'
    | '/courses/$slug'
    | '/payment/$slug'
    | '/tools/market-sessions'
    | '/tools/pip-calculator'
    | '/tools/trading-journal'
    | '/admin/'
    | '/auth/'
    | '/courses/'
    | '/tools/'
    | '/dashboard/trading-plan'
    | '/admin/students/$studentId'
    | '/courses/$slug/$lessonSlug'
    | '/dashboard/'
    | '/courses/$slug/'
    | '/dashboard/gift/$giftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alc-access'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/free'
    | '/mentorship'
    | '/reset-password'
    | '/sitemap.xml'
    | '/testimonials'
    | '/profile'
    | '/tips'
    | '/admin/alc-access'
    | '/admin/alc-library'
    | '/admin/certificates'
    | '/admin/lessons'
    | '/admin/mentorship-applications'
    | '/admin/payments'
    | '/admin/students'
    | '/admin/trading-tips'
    | '/auth/callback'
    | '/certificates/$certificateId'
    | '/payment/$slug'
    | '/tools/market-sessions'
    | '/tools/pip-calculator'
    | '/tools/trading-journal'
    | '/admin'
    | '/auth'
    | '/courses'
    | '/tools'
    | '/dashboard/trading-plan'
    | '/admin/students/$studentId'
    | '/courses/$slug/$lessonSlug'
    | '/dashboard'
    | '/courses/$slug'
    | '/dashboard/gift/$giftId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/alc-access'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/free'
    | '/mentorship'
    | '/reset-password'
    | '/sitemap.xml'
    | '/testimonials'
    | '/tools'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/tips'
    | '/admin/alc-access'
    | '/admin/alc-library'
    | '/admin/certificates'
    | '/admin/lessons'
    | '/admin/mentorship-applications'
    | '/admin/payments'
    | '/admin/students'
    | '/admin/trading-tips'
    | '/auth/callback'
    | '/certificates/$certificateId'
    | '/courses/$slug'
    | '/payment/$slug'
    | '/tools/market-sessions'
    | '/tools/pip-calculator'
    | '/tools/trading-journal'
    | '/admin/'
    | '/auth/'
    | '/courses/'
    | '/tools/'
    | '/_authenticated/dashboard/trading-plan'
    | '/admin/students/$studentId'
    | '/courses/$slug/$lessonSlug'
    | '/_authenticated/dashboard/'
    | '/courses/$slug/'
    | '/_authenticated/dashboard/gift/$giftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AlcAccessRoute: typeof AlcAccessRoute
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  FaqRoute: typeof FaqRoute
  FreeRoute: typeof FreeRoute
  MentorshipRoute: typeof MentorshipRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  AdminAlcAccessRoute: typeof AdminAlcAccessRoute
  AdminAlcLibraryRoute: typeof AdminAlcLibraryRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminMentorshipApplicationsRoute: typeof AdminMentorshipApplicationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminStudentsRoute: typeof AdminStudentsRouteWithChildren
  AdminTradingTipsRoute: typeof AdminTradingTipsRoute
  CertificatesCertificateIdRoute: typeof CertificatesCertificateIdRoute
  PaymentSlugRoute: typeof PaymentSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free': {
      id: '/free'
      path: '/free'
      fullPath: '/free'
      preLoaderRoute: typeof FreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alc-access': {
      id: '/alc-access'
      path: '/alc-access'
      fullPath: '/alc-access'
      preLoaderRoute: typeof AlcAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/trading-journal': {
      id: '/tools/trading-journal'
      path: '/trading-journal'
      fullPath: '/tools/trading-journal'
      preLoaderRoute: typeof ToolsTradingJournalRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/pip-calculator': {
      id: '/tools/pip-calculator'
      path: '/pip-calculator'
      fullPath: '/tools/pip-calculator'
      preLoaderRoute: typeof ToolsPipCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/market-sessions': {
      id: '/tools/market-sessions'
      path: '/market-sessions'
      fullPath: '/tools/market-sessions'
      preLoaderRoute: typeof ToolsMarketSessionsRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/payment/$slug': {
      id: '/payment/$slug'
      path: '/payment/$slug'
      fullPath: '/payment/$slug'
      preLoaderRoute: typeof PaymentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/certificates/$certificateId': {
      id: '/certificates/$certificateId'
      path: '/certificates/$certificateId'
      fullPath: '/certificates/$certificateId'
      preLoaderRoute: typeof CertificatesCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/trading-tips': {
      id: '/admin/trading-tips'
      path: '/admin/trading-tips'
      fullPath: '/admin/trading-tips'
      preLoaderRoute: typeof AdminTradingTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mentorship-applications': {
      id: '/admin/mentorship-applications'
      path: '/admin/mentorship-applications'
      fullPath: '/admin/mentorship-applications'
      preLoaderRoute: typeof AdminMentorshipApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/admin/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alc-library': {
      id: '/admin/alc-library'
      path: '/admin/alc-library'
      fullPath: '/admin/alc-library'
      preLoaderRoute: typeof AdminAlcLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alc-access': {
      id: '/admin/alc-access'
      path: '/admin/alc-access'
      fullPath: '/admin/alc-access'
      preLoaderRoute: typeof AdminAlcAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tips': {
      id: '/_authenticated/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof AuthenticatedTipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/courses/$slug/': {
      id: '/courses/$slug/'
      path: '/'
      fullPath: '/courses/$slug/'
      preLoaderRoute: typeof CoursesSlugIndexRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/courses/$slug/$lessonSlug': {
      id: '/courses/$slug/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/courses/$slug/$lessonSlug'
      preLoaderRoute: typeof CoursesSlugLessonSlugRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/admin/students/$studentId': {
      id: '/admin/students/$studentId'
      path: '/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AdminStudentsStudentIdRouteImport
      parentRoute: typeof AdminStudentsRoute
    }
    '/_authenticated/dashboard/trading-plan': {
      id: '/_authenticated/dashboard/trading-plan'
      path: '/trading-plan'
      fullPath: '/dashboard/trading-plan'
      preLoaderRoute: typeof AuthenticatedDashboardTradingPlanRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/gift/$giftId': {
      id: '/_authenticated/dashboard/gift/$giftId'
      path: '/gift/$giftId'
      fullPath: '/dashboard/gift/$giftId'
      preLoaderRoute: typeof AuthenticatedDashboardGiftGiftIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardTradingPlanRoute: typeof AuthenticatedDashboardTradingPlanRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardGiftGiftIdRoute: typeof AuthenticatedDashboardGiftGiftIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardTradingPlanRoute:
      AuthenticatedDashboardTradingPlanRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardGiftGiftIdRoute:
      AuthenticatedDashboardGiftGiftIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTipsRoute: typeof AuthenticatedTipsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTipsRoute: AuthenticatedTipsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CoursesSlugRouteChildren {
  CoursesSlugLessonSlugRoute: typeof CoursesSlugLessonSlugRoute
  CoursesSlugIndexRoute: typeof CoursesSlugIndexRoute
}

const CoursesSlugRouteChildren: CoursesSlugRouteChildren = {
  CoursesSlugLessonSlugRoute: CoursesSlugLessonSlugRoute,
  CoursesSlugIndexRoute: CoursesSlugIndexRoute,
}

const CoursesSlugRouteWithChildren = CoursesSlugRoute._addFileChildren(
  CoursesSlugRouteChildren,
)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface ToolsRouteChildren {
  ToolsMarketSessionsRoute: typeof ToolsMarketSessionsRoute
  ToolsPipCalculatorRoute: typeof ToolsPipCalculatorRoute
  ToolsTradingJournalRoute: typeof ToolsTradingJournalRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsMarketSessionsRoute: ToolsMarketSessionsRoute,
  ToolsPipCalculatorRoute: ToolsPipCalculatorRoute,
  ToolsTradingJournalRoute: ToolsTradingJournalRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

interface AdminStudentsRouteChildren {
  AdminStudentsStudentIdRoute: typeof AdminStudentsStudentIdRoute
}

const AdminStudentsRouteChildren: AdminStudentsRouteChildren = {
  AdminStudentsStudentIdRoute: AdminStudentsStudentIdRoute,
}

const AdminStudentsRouteWithChildren = AdminStudentsRoute._addFileChildren(
  AdminStudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AlcAccessRoute: AlcAccessRoute,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  FaqRoute: FaqRoute,
  FreeRoute: FreeRoute,
  MentorshipRoute: MentorshipRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  AdminAlcAccessRoute: AdminAlcAccessRoute,
  AdminAlcLibraryRoute: AdminAlcLibraryRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminMentorshipApplicationsRoute: AdminMentorshipApplicationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminStudentsRoute: AdminStudentsRouteWithChildren,
  AdminTradingTipsRoute: AdminTradingTipsRoute,
  CertificatesCertificateIdRoute: CertificatesCertificateIdRoute,
  PaymentSlugRoute: PaymentSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
