begin;
alter table public.alc_access_requests add column if not exists public_review_message text;
do $constraints$ begin if not exists (select 1 from pg_constraint where conname='alc_access_public_message_length' and conrelid='public.alc_access_requests'::regclass) then alter table public.alc_access_requests add constraint alc_access_public_message_length check (coalesce(char_length(public_review_message),0)<=500); end if; end $constraints$;
create table if not exists public.alc_access_modules (id uuid primary key default gen_random_uuid(),title text not null,description text,sort_order integer not null default 0,is_published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(char_length(title) between 1 and 160),check(coalesce(char_length(description),0)<=1000));
alter table public.alc_access_modules enable row level security;
alter table public.alc_access_videos add column if not exists module_id uuid references public.alc_access_modules(id) on delete cascade;
alter table public.alc_access_videos add column if not exists sort_order integer;
update public.alc_access_videos set sort_order=0 where sort_order is null;
alter table public.alc_access_videos alter column sort_order set not null;

-- Returned row types changed from the initial ALC RPCs. PostgreSQL requires a
-- drop before changing OUT/RETURNS TABLE columns; preserve tables and data.
drop function if exists public.alc_access_my_request();
drop function if exists public.alc_access_library();
drop function if exists public.admin_list_alc_access_requests(text);
drop function if exists public.admin_list_alc_access_requests(text, text, integer, text);
drop function if exists public.admin_review_alc_access_request(uuid, text, text);
drop function if exists public.admin_review_alc_access_request(uuid, text, text, text);
drop function if exists public.admin_alc_access_pending_count();
create or replace function public.alc_access_my_request() returns table(id uuid,status text,created_at timestamptz,reviewed_at timestamptz,program text,study_year integer,public_review_message text) language sql security invoker set search_path=public as $$ select id,status,created_at,reviewed_at,program,study_year,public_review_message from public.alc_access_requests where user_id=auth.uid() order by created_at desc limit 1 $$;
create or replace function public.alc_access_library() returns table(module_id uuid,module_title text,module_description text,module_order integer,id uuid,title text,description text,video_url text,video_order integer) language sql security invoker set search_path=public as $$ select m.id,m.title,m.description,m.sort_order,v.id,v.title,v.description,v.video_url,v.sort_order from public.alc_access_modules m join public.alc_access_videos v on v.module_id=m.id where m.is_published and v.is_published and exists(select 1 from public.alc_access_requests r where r.user_id=auth.uid() and r.status='approved') order by m.sort_order,v.sort_order $$;
create or replace function public.admin_list_alc_access_requests(p_status text default 'all',p_search text default '',p_year integer default null,p_program text default null) returns table(id uuid,user_id uuid,full_name text,study_year integer,email text,phone text,program text,other_program text,additional_details text,status text,admin_notes text,public_review_message text,created_at timestamptz,reviewed_at timestamptz) language sql security invoker set search_path=public as $$ select r.id,r.user_id,r.full_name,r.study_year,r.email,r.phone,r.program,r.other_program,r.additional_details,r.status,r.admin_notes,r.public_review_message,r.created_at,r.reviewed_at from public.alc_access_requests r where public.is_admin() and (p_status='all' or r.status=p_status) and (p_year is null or r.study_year=p_year) and (p_program is null or r.program=p_program) and (p_search='' or concat_ws(' ',r.full_name,r.email,r.phone,left(r.id::text,8)) ilike '%'||trim(p_search)||'%') order by r.created_at desc $$;
create or replace function public.admin_review_alc_access_request(p_request_id uuid,p_status text,p_admin_notes text default null,p_public_review_message text default null) returns table(id uuid,status text,reviewed_at timestamptz) language plpgsql security invoker set search_path=public as $$ begin if not public.is_admin() then raise exception 'Administrator access required'; end if; if p_status not in ('approved','rejected') or coalesce(char_length(p_admin_notes),0)>1000 or coalesce(char_length(p_public_review_message),0)>500 then raise exception 'Invalid review'; end if; update public.alc_access_requests set status=p_status,admin_notes=nullif(trim(p_admin_notes),''),public_review_message=nullif(trim(p_public_review_message),''),reviewed_by=auth.uid(),reviewed_at=now(),updated_at=now() where id=p_request_id; if not found then raise exception 'Request not found';end if;return query select r.id,r.status,r.reviewed_at from public.alc_access_requests r where r.id=p_request_id;end $$;
create or replace function public.admin_alc_access_pending_count() returns integer language sql security invoker set search_path=public as $$ select count(*)::integer from public.alc_access_requests where public.is_admin() and status='pending' $$;
grant execute on function public.alc_access_my_request(),public.alc_access_library(),public.admin_list_alc_access_requests(text,text,integer,text),public.admin_review_alc_access_request(uuid,text,text,text),public.admin_alc_access_pending_count() to authenticated;
commit;
